/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#2d3436",
        "on-secondary-container": "#4f685a",
        "surface-tint": "#586062",
        "on-surface": "#1a1c1b",
        "tertiary-container": "#522715",
        "primary-fixed-dim": "#c1c8ca",
        "on-secondary-fixed-variant": "#334c3f",
        "on-secondary-fixed": "#072015",
        "primary": "#181f21",
        "primary-fixed": "#dde4e6",
        "surface-container-highest": "#e3e2e0",
        "surface-container-high": "#e9e8e6",
        "on-surface-variant": "#434749",
        "surface-variant": "#e3e2e0",
        "outline": "#747879",
        "on-primary-fixed-variant": "#41484a",
        "secondary-fixed": "#cde9d7",
        "secondary-container": "#cae6d4",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#fcb69d",
        "on-error": "#ffffff",
        "on-background": "#1a1c1b",
        "background": "#faf9f7",
        "inverse-surface": "#2f3130",
        "on-tertiary-fixed-variant": "#6a3a27",
        "surface-container-low": "#f4f3f1",
        "on-tertiary-container": "#cb8c74",
        "surface": "#faf9f7",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbce",
        "on-primary-fixed": "#161d1f",
        "tertiary": "#381304",
        "surface-container": "#efeeec",
        "secondary": "#4b6456",
        "surface-dim": "#dadad8",
        "outline-variant": "#c3c7c8",
        "on-error-container": "#93000a",
        "on-primary-container": "#959c9f",
        "inverse-on-surface": "#f1f1ef",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#341003",
        "inverse-primary": "#c1c8ca",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#faf9f7",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b1cdbc"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "gutter": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "margin": "1.25rem",
        "space-xs": "0.25rem",
        "space-xl": "2.25rem"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
